apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: wsi-nodepool
spec:
  template:
    spec:
      taints:
        - key: wsi-nodepool
          effect: NoSchedule
      requirements:
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["c5.large", "c5.xlarge"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: wsi-nodeclass
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 60s
  limits:
    cpu: "8"
    memory: "16Gi"
