[PARSER]
    Name        book_access
    Format      regex
    Regex       ^\d{4}/\d{2}/\d{2}\s+\d{2}:\d{2}:\d{2}\s+access\s+method=(?<method>\S+)\s+path=(?<path>\S+)\s+status=(?<status>\d+)\s+duration=(?<duration>\S+)\s+remote_addr=(?<remote_addr>\S+)\s+user_agent="(?<user_agent>[^"]*)"$
