{
 "title": "wsc-eks-dashboard",
 "tags": [ "wsc" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "TOTAL_NODE_GROUP_COUNT",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "count(kube_node_info)" }
   ]
  },
  {
   "title": "APP_POD_COUNT",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"wsc\"})"
    }
   ]
  },
  {
   "title": "NODE_GROUP_CPU_USAGE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]))"
    }
   ]
  },
  {
   "title": "NODE_GROUP_MEMORY_USAGE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum by (instance) (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes)"
    }
   ]
  },
  {
   "title": "APP_POD_CPU_USAGE",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"wsc\", pod=~\"wsc-deploy.*\", container!=\"\"}[5m]))"
    }
   ]
  },
  {
   "title": "APP_POD_MEMORY_USAGE",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"wsc\", pod=~\"wsc-deploy.*\", container!=\"\"})"
    }
   ]
  }
 ]
}