apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-deploy
  namespace: worldpay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book
  template:
    metadata:
      labels:
        app: book
    spec:
      serviceAccountName: book-sa
      containers:
      - name: book
        image: ACCOUNT_ID.dkr.ecr.ap-northeast-2.amazonaws.com/worldpay-book:v1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: AWS_REGION
          value: "ap-northeast-2"
        - name: TABLE_NAME
          value: "Concerts"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
