{
 "title": "WSC2026 Container Logs",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Any Log",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{namespace=\"wsc-app-log\"}"
    }
   ]
  },
  {
   "title": "INFO Log Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count_over_time({namespace=\"wsc-app-log\"} |= \"INFO\" [1m])"
    }
   ]
  },
  {
   "title": "ERROR Log Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "count_over_time({namespace=\"wsc-app-log\"} |= \"ERROR\" [1m])"
    }
   ]
  },
  {
   "title": "WARNING Log Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "count_over_time({namespace=\"wsc-app-log\"} |= \"WARNING\" [1m])"
    }
   ]
  }
 ]
}